### ISSUE TITLE
Element should be visible {WebDriverException: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?}

### ISSUE THREAD

**Issue by AntonSyl** [selenide/selenide-appium#10]
```
Jan 03, 2018 9:53:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Jan 03, 2018 9:53:29 AM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
INFO: BrowserName= Version= Platform=ANDROID
Jan 03, 2018 9:53:29 AM com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
INFO: Selenide v. 4.9.1
Jan 03, 2018 9:53:29 AM com.codeborne.selenide.webdriver.WebDriverFactory logSeleniumInfo
INFO: Selenium WebDriver v. 3.8.1 build time: 2017-12-01T18:33:54.468Z
Jan 03, 2018 9:53:29 AM com.codeborne.selenide.impl.WebDriverThreadLocalContainer createDriver
INFO: Create webdriver in current thread 1: AndroidDriver -> Android: UiAutomator2

Element not found {WebDriverException: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?}
Expected: exist

Screenshot: file:/C:/Users/antonsy/Projects/test/build/reports/tests/1514966013926.0.png
Page source: file:/C:/Users/antonsy/Projects/test/build/reports/tests/1514966013926.0.html
Timeout: 4 s.
Caused by: WebDriverException: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:116)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at com.test.tests.seaptest.login1(seaptest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.openqa.selenium.WebDriverException: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'ANTONSY-PC', ip: '192.168.38.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:170)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:76)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:95)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.sendKeys(<generated>)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
	... 27 more
Caused by: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'ANTONSY-PC', ip: '192.168.38.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:131)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:38)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:55)
	at io.appium.java_client.HasSessionDetails.isBrowser(HasSessionDetails.java:79)
	at io.appium.java_client.AppiumDriver.isBrowser(AppiumDriver.java:268)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.lambda$0(WebDriverUnpackUtility.java:96)
	at java.util.Optional.map(Optional.java:215)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.getCurrentContentType(WebDriverUnpackUtility.java:92)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElement(ContentMappedBy.java:36)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:96)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:150)
	... 37 more
```

Test script 

```
public class Login{
    private static final LoginPage loginPage = new LoginPage();

    @BeforeMethod
    public void setUp()  {
        Configuration.browser = AndroidDriverProvider.class.getName();
//        screen(loginPage);
    }

    @AfterMethod
    public void tearDown1() {
        close();
    }

    @Test
    public void login(){
        screen(loginPage);
        loginPage.emailField.sendKeys("test@test.net");
        loginPage.continueBtn.click();

    }

    @Test
    public void login1(){
        screen(loginPage);
        loginPage.emailField.sendKeys("test@test.net");
        loginPage.continueBtn.click();
    }
}
```
The first test is passed but the second one has an error

**Comment by rosolko** [comment]
@AntonSyl Change `Before/AfterMethod` to `Before/AfterClass` and place `getAndroidDriver().closeApp()`  to `AfterMethod` and try to rerun tests.

**Comment by asolntsev** [comment]
@AntonSyl Hei, did you try the suggested solution? Does it help?

**Comment by AntonSyl** [comment]
Okay, now I have such problem. The first test is passed but application was not closed.
I want to close application after first test and launch before second test

**Comment by rosolko** [comment]
@AntonSyl 
`getAndroidDriver().closeApp()` call inside `AfterMethod` should close application.
Inside next test selenide automatically should start driver if it was closed.

**Comment by AntonSyl** [comment]
@rosolko 
@BeforeClass
```
    public void setUp()  {
        Configuration.browser = AndroidDriverProvider.class.getName();
    }

    @AfterClass
    public void tearDown1() {
       AndroidDriverProvider.driver.closeApp();

    }
```
but selenide not close application after first test

**Comment by rosolko** [comment]
@AntonSyl Misunderstanding
Just replace annotation `AfterClass` with `AfterMethod`
And `AndroidDriverProvider.driver.closeApp();` with `((AndroidDriver) WebDriverRunner.getWebDriver()).closeApp();`

**Comment by AntonSyl** [comment]
Okay. I done that, and after first test application is close. But before second test the driver not start. Maybe not enough time for launch application

**Comment by rosolko** [comment]
@AntonSyl 
Can you please show me content of `AndroidDriverProvider` class

**Comment by AntonSyl** [comment]
@rosolko 
Here it is 
```
public class AndroidDriverProvider implements WebDriverProvider {
public static AndroidDriver driver;
@Override
    public WebDriver createDriver(DesiredCapabilities desiredCapabilities) {
        Configuration.captureJavascriptErrors =false;
        Configuration.startMaximized =false;
        DesiredCapabilities capabilities = new DesiredCapabilities();
        PLATFORM = "Android";
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("platformName", PLATFORM);
        capabilities.setCapability("platformVersion", "7.1.2");
        capabilities.setCapability("deviceName", "aaaaa");
        capabilities.setCapability("autoGrantPermissions", "true");
        capabilities.setCapability("udid", "LGD724273e98ee");
        capabilities.setCapability("resetKeyboard", true);
        capabilities.setCapability("unicodeKeyboard", true);
        capabilities.setCapability("appPackage", "com.scedule.app");
        capabilities.setCapability("appActivity", "com.scedule.app.SplashActivity");
        try {
            return new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by rosolko** [comment]
@AntonSyl 
Change `appActivity` to `appWaitActivity`.
And add `deviceReadyTimeout` with for example `120` value.

**Comment by AntonSyl** [comment]
```
java.lang.IllegalArgumentException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot stop and clear com.scedule.app. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\antonsy\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s LGD724273e98ee shell pm clear com.scedule.app' exited with code 1'; Stderr: 'Failed'; Code: '1' (WARNING: The server did not provide any stacktrace information)
```

**Comment by rosolko** [comment]
@AntonSyl from now it's appium side errors

**Comment by AntonSyl** [comment]
@rosolko Thank you. Will find solution for this problem
