### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented

### ISSUE THREAD

**Issue by myself521** [selenide/selenide-appium#14]
```java
Traceback (most recent call last):
  File "D:/PycharmProject/untitled/H5.py", line 36, in <module>
    dr.swipe(start_x=200,start_y=200,end_x=200,end_y=0,duration=1000)
  File "D:\PycharmProject\untitled\venv\python2.7\lib\site-packages\appium\webdriver\extensions\action_helpers.py", line 115, in swipe
    action.perform()
  File "D:\PycharmProject\untitled\venv\python2.7\lib\site-packages\appium\webdriver\common\touch_action.py", line 103, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "D:\PycharmProject\untitled\venv\python2.7\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\PycharmProject\untitled\venv\python2.7\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```
 
**Test_Script**
```java
dr = webdriver.Remote('http://127.0.0.1:4723/wd/hub',des)
dr.swipe(start_x=200,start_y=200,end_x=200,end_y=0,duration=1000)
```

Python:2.7.16
Appium:1.9.0
android:8.0.0
node:10.15.1

I want use swipe to control screen to scroll,but i got a error message, I have check some information,no answer;

**Comment by rosolko** [comment]
@myself521 Python?
