### ISSUE TITLE
'terminateApp()' method not working as expected

### ISSUE THREAD

**Issue by umesh-Ideahub** [selenide/selenide-appium#145]
**The problem**
I'm currently using appium-selenide with cucumber, and I'm trying to get a fresh session before executing each feature file. While doing that, I have used a method called 'terminateApp()' in 'SelenideAppium' class. After the execution, I'm getting 'Unknown mobile command "terminateApp"' and application not getting terminated as expected (Refer stacktrace attached).

**Environment**
Selenide-Appium Version - 2.6.1
Android - 13 (emulator)

** Code To Reproduce Issue**
I have scenario called 'setup' in every feature file which initiate appium session and perform login operation
`// Runs before scenarios with @Setup tag
    @Before("@Setup")
    public static void beforeTest(){
        SelenideAppium.terminateApp("com.XXX.DigitalApp.devXXX");
    }
`
**Stacktrance**
`org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "terminateApp". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,deleteFile,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock commands are supported.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [4d29628c-543a-4c31-896c-8b396cd8f456, executeScript {script=mobile:terminateApp, args=[{appId=com.XXX.DigitalApp.devXXX}]}]
Capabilities {appium:app: C:\Users\Umesh Perera\Docum..., appium:appPackage: com.hnb.DigitalApp.devHnb, appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\Umesh Perera\Docum..., automationName: UIAutomator2, deviceName: Android Emulator, fullReset: false, newCommandTimeout: 20, platformName: android, platformVersion: 13.0}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone64_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 440, appium:deviceScreenSize: 1080x2220, appium:deviceUDID: emulator-5554, appium:fullReset: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 20, appium:pixelRatio: 2.75, appium:platformVersion: 13, appium:statBarHeight: 66, appium:takesScreenshot: true, appium:viewportRect: {height: 2088, left: 0, top: 66, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 4d29628c-543a-4c31-896c-8b396cd8f456

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
	at com.codeborne.selenide.appium.AppiumNavigator.lambda$terminateApp$0(AppiumNavigator.java:33)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:105)
	at com.codeborne.selenide.appium.AppiumNavigator.terminateApp(AppiumNavigator.java:24)
	at com.codeborne.selenide.appium.SelenideAppium.terminateApp(SelenideAppium.java:57)
	at cucumber.MobileSteps.beforeTest(MobileSteps.java:314)
`

**Comment by amuthansakthivel** [comment]
Hi @umesh-Ideahub -You should pass the "package name" of the android app and not the "android activity"
