### ISSUE TITLE
WebDriverException: Method has not yet been implemented at `shouldHave(text())` method

### ISSUE THREAD

**Issue by uNl1m** [selenide/selenide-appium#3]
```Jul 04, 2017 9:45:18 PM com.codeborne.selenide.Selenide getJavascriptErrors
SEVERE: org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 23 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Antons-MacBook-Pro.local', ip: '192.168.0.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_121'
Driver info: im.radius.drivers.SwipeableDriver
Capabilities [{appPackage=im.lala.android, deviceScreenSize=1080x1920, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=ZLQOKVP7RG7SYT8H, platform=LINUX, deviceUDID=ZLQOKVP7RG7SYT8H, appActivity=com.lala.core.screens.welcome.SplashScreen, desired={appPackage=im.lala.android, appActivity=com.lala.core.screens.welcome.SplashScreen, automationName=Appium, platformName=Android, deviceName=UO85B6SO99999999, resetKeyboard=true}, platformVersion=6.0, webStorageEnabled=false, locationContextEnabled=false, automationName=Appium, takesScreenshot=true, javascriptEnabled=true, deviceModel=VFD 700, platformName=Android, deviceManufacturer=Vodafone, resetKeyboard=true}]
Session ID: b2e22741-0ddb-4718-9aea-759321310dfd
Jul 04, 2017 9:45:18 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Close webdriver: 1 -> SwipeableDriver:  on LINUX (b2e22741-0ddb-4718-9aea-759321310dfd)
Jul 04, 2017 9:45:18 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Close proxy server: 1 -> null
Jul 04, 2017 9:45:18 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser run
INFO: Trying to close the browser SwipeableDriver ...
Jul 04, 2017 9:45:22 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Closed webdriver in 3384 ms

Element should have text 'Please enable permissionsSs' {By.className: android.widget.TextView}
Element: 'WebDriverException: Method has not yet been implemented'```

**Comment by asolntsev** [comment]
@unlimUA Damn, Appium is a scam. Scam everywhere. :(

`AndroidDriver` implements `JavascriptExecutor`, but its method `executeScript` throws "Method has not yet been implemented" error:

```
org.openqa.selenium.WebDriverException: Method has not yet been implemented
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:573)
	at com.codeborne.selenide.Selenide.executeJavaScript(Selenide.java:465)
```

**Comment by asolntsev** [comment]
@unlimUA There is more surprises. Method `getAttribute` throws an error `An element could not be located` for element that definitely exists:

```
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:124)
	at com.codeborne.selenide.impl.Describe.attr(Describe.java:77)
```

**Comment by asolntsev** [comment]
@unlimUA In given circumstances, it's hard to show anything more in Selenide error message. What you suggest?

**Comment by unlimUA** [comment]
@asolntsev I think you should do something like at web automation 
`
Element should have text 'Что такое Selenide?1' {#support}
Element: '<a href="/support" id="support">Коммерческая поддержка</a>'`

**Comment by unlimUA** [comment]
@asolntsev  I create this function and use it 
`public static void assertTexts(String expactedText, SelenideElement element){
        assertEquals(expactedText,element.getText());
    }`

**Comment by asolntsev** [comment]
@unlimUA I agree with you, Selenide should write an error message like this:

```
Element should have text 'Что такое Selenide?1' {#support} Element: '<a href="/support" id="support">Коммерческая поддержка</a>'
```

I started researching this problem and found that it's not trivial. 

Meanwhile, can you say how you declare the element? Do you use `$` or something like `@AndroidFindBy`?

**Comment by unlimUA** [comment]
I use `$("element")`

**Comment by asolntsev** [comment]
I think it was fixed a long time ago.
At least in latest version `selenide-appium:1.6.0` for sure.
