### ISSUE TITLE
There is no MobileDriver in Appium 8.0.0, changed to AppiumDriver

### ISSUE THREAD

**Issue by sobolewska** [selenide/selenide-appium#66]
There is no `MobileDriver` in Appium 8.0.0.
`AppiumClick` tries to import `import io.appium.java_client.MobileDriver;`

When selenide-appium is added to dependencies, the `element.click()` method fails with error:

```
NoClassDefFoundError: io/appium/java_client/MobileDriver
Screenshot: file: ...
Page source: file: ...
Timeout: 4 s.
Caused by: java.lang.NoClassDefFoundError: io/appium/java_client/MobileDriver
	at app//com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:103)
	at app//com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:86)
	at app//com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:75)
	at app//com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:88)
	at app/jdk.proxy3/jdk.proxy3.$Proxy34.click(Unknown Source)
	at app//****.ipad.LoginPage.loginAsUser(LoginPage.java:24)
	(...)
```

(see also: https://github.com/selenide/selenide/issues/1751#issuecomment-1062709968)

**Comment by asolntsev** [comment]
@sobolewska Yes, currently `selenide-appium` works only on Appium 7. 
Appium 8 was released recently, so now we can upgrade to Appium 8. 

Feel free to help us! See https://github.com/selenide/selenide-appium/issues/65

**Comment by sobolewska** [comment]
@asolntsev I'll try to help :) but not promising anything, as I have more experience with Python than Java.
