### ISSUE TITLE
Method `setLoadTimeout` is not supported by `AppiumDriver`. Consider about allow nullifying `pageLoadTimeout` configuration.

### ISSUE THREAD

**Issue by rosolko** [selenide/selenide-appium#68]
Possible fix - allow to setup config with:

```java
Configuration.pageLoadTimeout = null;
```

Selenide problem code:

```java
private void setLoadTimeout(Config config, WebDriver webdriver) {
    try {
      webdriver.manage().timeouts().pageLoadTimeout(Duration.ofMillis(config.pageLoadTimeout()));
    }
    catch (UnsupportedCommandException e) {
      log.info("Failed to set page load timeout to {} ms: {}", config.pageLoadTimeout(), e.toString());
    }
    catch (RuntimeException e) {
      log.error("Failed to set page load timeout to {} ms", config.pageLoadTimeout(), e);
    }
  }
```

Found by logs:

```java
Caused by: java.lang.IllegalArgumentException: Cannot decode response content: {"status":405,"value":{"message":"Not implemented yet for pageLoad."},"sessionId":"95a77276b7948a58665889c0ca11c9b3421fc390"}
	at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:86)
	at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:47)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
	... 117 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: {"status":405,"value":{"message":"Not implemented yet for pageLoad."},"sessionId":"95a77276b7948a58665889c0ca11c9b3421fc390"}
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:83)
	... 121 more
```

**Comment by rosolko** [comment]
Research a little bit and it works as expected. Not throw an exception in case of not supported operation, just log it.
