### ISSUE TITLE
ClassCastException in Drag'n'Drop

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide-appium#75]
When
* using Drag'n'Drop method with a driver which is wrapped to a listener, 

Then
* I am getting ClassCastException:

```java
java.lang.ClassCastException: org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement cannot be cast to org.openqa.selenium.remote.RemoteWebElement
	at io.appium.java_client.touch.offset.ElementOption.withElement(ElementOption.java:89)
	at io.appium.java_client.touch.offset.ElementOption.element(ElementOption.java:49)
	at com.codeborne.selenide.appium.commands.AppiumDragAndDropTo.execute(AppiumDragAndDropTo.java:35)
	at com.codeborne.selenide.appium.commands.AppiumDragAndDropTo.execute(AppiumDragAndDropTo.java:20)
```

**Comment by BorisOsipov** [comment]
@asolntsev seems fixed in https://github.com/selenide/selenide-appium/commit/e4c3daac8d80e04d6691a85236379b5cf584d70f isn't it?

**Comment by asolntsev** [comment]
Yes, seems so. Thanks.
